### ISSUE TITLE
Replace description

### ISSUE THREAD

**Issue by D-mercool** [drobotun/gostcrypto#2]
В функции:
[https://github.com/drobotun/gostcrypto/blob/master/gostcrypto/gosthash/gost_34_11_2012.py#L673](url)

Следует исправить описание:

- [ ] streebog256 возвращает строку длины **64**, а не 32
- [ ] streebog512 возвращает строку длины **128**, а не 64

Спасибо за библиотеку ))

**Comment by drobotun** [comment]
В описании написано все правильно. В этом описании речь не идёт о возврате результата подсчёта хэш-функции в виде строки. Речь идёт о том, что размер хэша (в числовом выражении, а не в виде строки в шестнадцатеричном представлении) для "streebog256" равен 32 байтам, а для "streebog512" равен 64 байта.
