### ISSUE TITLE
Ошибка в реализации HMAC/HASH?

### ISSUE THREAD

**Issue by CheerfulGrape** [drobotun/gostcrypto#3]
Добрый день! Большое спасибо за референс, который можно потыкать. Попробовал взять пример
```Python
import gostcrypto

key = bytearray.fromhex('000102030405060708090a0b0c0d0e0f1011121315161718191a1b1c1d1e1f')
data = bytearray.fromhex('0126bdb87800af214341456563780100')

hmac_obj = gostcrypto.gosthmac.new('HMAC_GOSTR3411_2012_256', key, data=b'')
hmac_obj.update(data)
hmac_obj.hexdigest()
```
Результат, соответственно
```
456734ebf2c1a59a131de7fd8b52e60a335341dbc943242c8ce7e3d62ad3c0f4
```

Что не соответствует Р 50.1.113-2016 (https://tc26.ru/standard/rs/Р%2050.1.113-2016.pdf), там
```
a1aa5f7de402d7b3d323f2991c8d4534013137010a83754fd0af6d7cd4922ed9
```
при тех же вводных

Это я чего-то не понимаю/не так делаю, или в коде ошибка?

P.S. Ещё, если я правильно понял, то по ГОСТу на `update` подаются последние 512 бит (M = M' | m, берётся m), а не первые, а в коде вроде первые. Т. е. ключ должен закидываться на последней итерации, а не на первой

**Comment by CheerfulGrape** [comment]
Похоже, я где-то опечатался, попробовал ещё раз - всё совпадает...

**Comment by CheerfulGrape** [comment]
Если вдруг кто-то ещё будет в этом копаться (сомневаюсь), то проблема была в том, что ГОСТ 34.11 использует обратную нумерацию байт. Т. е. для 16-байтового массива индексы будут (a15, a14, ..., a0). Это влияет на то, как применяется хэш. Несмотря на то, что там берутся последние 512 бит (64 байта) и это дублируется в примерах, по факту, на реальных данных, нужно брать первые 64байта (и, если реализовать алгоритм точно по ГОСТу - нужно ещё порядок байт инверсировать). 

Ну либо же писать, учитывая это, как сделано тут. Ещё раз огромное спасибо, без этого примера, который можно поковырять и внутренние значения посмотреть, я бы, наверное, не разобрался

**Comment by drobotun** [comment]
Это все написано в ГОСТе, правда стиль изложения тяжеловат и с первого раза вкурить не всегда получается...
--
Отправлено из Mail.ru для Android суббота, 21 сентября 2024г., 01:25 +03:00 от CheerfulGrape  ***@***.*** :
