### ISSUE TITLE
Режимы шифрования Кузнечика не работают

### ISSUE THREAD

**Issue by NimalizTheFox** [drobotun/gostcrypto#4]
Приветствую!
Тестировал разные режимы шифрования Кузнечика и обнаружил, что, кроме ECB, ни один не работает (или я что-то делаю не правильно).
Код, которым тестировал:
```python
import gostcrypto
from random import randbytes

key = bytearray(b"Keyisimportatnpartofthisprogramm")
text = randbytes(32)
print(text)

ba_text = bytearray(text)

cipher_obj = gostcrypto.gostcipher.new('kuznechik',
                                       key,
                                       gostcrypto.gostcipher.MODE_ECB)

cipher_text = cipher_obj.encrypt(ba_text)

uncipher_text = cipher_obj.decrypt(cipher_text)
print(bytes(uncipher_text))
```
Менял только режим шифрования. Две выводящиеся строки полностью совпадают только при MODE_ECB.

**Из наблюдений:**
Если взять в качестве текста строку подлиннее:
```python
text = "Веселая часть шифрования в том, что оно может не получиться.".encode("utf-8")
```
то, при режимах CBC и CFB, расшифрованная байтовая строка будет совпадать после, кажется, первого блока (легче обнаружить, если смотреть с конца):
```
b'\xd0\x92\xd0\xb5\xd1\x81\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x8f \xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd1\x8c \xd1\x88\xd0\xb8\xd1\x84\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xb2 \xd1\x82\xd0\xbe\xd0\xbc, \xd1\x87\xd1\x82\xd0\xbe \xd0\xbe\xd0\xbd\xd0\xbe \xd0\xbc\xd0\xbe\xd0\xb6\xd0\xb5\xd1\x82 \xd0\xbd\xd0\xb5 \xd0\xbf\xd0\xbe\xd0\xbb\xd1\x83\xd1\x87\xd0\xb8\xd1\x82\xd1\x8c\xd1\x81\xd1\x8f.'
b'\xfbj>\x18\xebV\xafy\x7fV(\x10\xab\xfa\x99M\xa9\x19\xbf\x99 \x8b\x7f\xe0\xc1\xc8\x19Lf\x11\xf0\x01\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xb2 \xd1\x82\xd0\xbe\xd0\xbc, \xd1\x87\xd1\x82\xd0\xbe \xd0\xbe\xd0\xbd\xd0\xbe \xd0\xbc\xd0\xbe\xd0\xb6\xd0\xb5\xd1\x82 \xd0\xbd\xd0\xb5 \xd0\xbf\xd0\xbe\xd0\xbb\xd1\x83\xd1\x87\xd0\xb8\xd1\x82\xd1\x8c\xd1\x81\xd1\x8f.\x00\x00\x00'
```

**Comment by drobotun** [comment]
Добрый день. Не забывайте про остальные параметры шифрования для остальных режимов кроме ECB - инициализационный вектор, режим паддинга...
--
Отправлено из Mail.ru для Android вторник, 17 декабря 2024г., 00:40 +03:00 от NimalizTheFox  ***@***.*** :

**Comment by NimalizTheFox** [comment]
Кажется, проблема не в этом. Как минимум, насколько я понял код функции new, вектору инициализации и режиму паддинга, при отсутствии их аргументов при вызове функции, назначаются значения по умолчанию, которые _DEFAULT_IV_KUZNECHIK и PAD_MODE_1 соотвественно (для режима шифрования CBC). Четкое их указание в вызове функции new 
```python
cipher_obj = gostcrypto.gostcipher.new('kuznechik',
                                       key,
                                       gostcrypto.gostcipher.MODE_CBC,
                                       init_vect=gostcrypto.gostcipher.gost_34_13_2015._DEFAULT_IV_KUZNECHIK,
                                       pad_mode=gostcrypto.gostcipher.gost_34_13_2015.PAD_MODE_1)
```
не привели к другому результату, строка исходного текста и расшифрованного шифротекста все еще не совпадают.

**Comment by NimalizTheFox** [comment]
Немного разобрался в коде и пришел к выводу, что виновата функция **_set_init_vect**. Она переписывает изначальный вектор инициализации, из-за чего первый блок при расшифровке в том же режиме CBC использует вектор инициализации последнего блока, полученного при шифровании, а не изначальный ВИ. 
Если объявить cipher_obj заново с теми же параметрами, что использовались для шифрования, то он сможет расшифровать шифротекст правильно и исходный и расшифрованный текст сойдутся.
```python
import gostcrypto
from random import randbytes

key = bytearray(b"Keyisimportatnpartofthisprogramm")
text = "Веселая часть шифрования в том, что оно может не получиться.".encode("utf-8")
print(text)
ba_text = bytearray(text)

init_vect = bytearray(randbytes(32))
cipher_obj = gostcrypto.gostcipher.new('kuznechik',
                                       key,
                                       gostcrypto.gostcipher.MODE_CBC,
                                       init_vect=init_vect)

cipher_text = cipher_obj.encrypt(ba_text)

cipher_obj = gostcrypto.gostcipher.new('kuznechik',
                                       key,
                                       gostcrypto.gostcipher.MODE_CBC,
                                       init_vect=init_vect)

uncipher_text = cipher_obj.decrypt(cipher_text)
print(bytes(uncipher_text))
```

**Comment by drobotun** [comment]
Дело в том что значение инициализационного вектора изменяется в процессе шифрования, и когда начинается расшифровка, инициализационный вектор берется уже с измененным значением. Для корректной работы нужно создавать отдельные экземпляры cipher_obj для зашифровывания и для расшифровывания. Либо при расшифровывании задавать инициализационный вектор заново, таким же значением,как и при зашифровании.
--
Отправлено из Mail.ru для Android вторник, 17 декабря 2024г., 11:02 +03:00 от NimalizTheFox  ***@***.*** :
